config/routes.rb
Rails.application.routes.draw do
  post 'sessions/create'
  delete 'sessions/destroy'
  post 'users/create'
  root 'videos#index'
  get '/websocket', to: 'videos#websocket'
  get '/share', to: 'videos#share'
  post '/share', to: 'videos#share'
  post '/video_action', to: 'videos#video_action'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/likeable.rb
class Likeable < ApplicationRecord
  belongs_to :video
  belongs_to :user

  validates :video_id, uniqueness: { scope: :user_id, message: "One User only like one video!!!" }
  validates :status, presence: true

  enum status: [:like, :dislike]
end

app/models/user.rb
class User < ApplicationRecord

  has_many :videos
  has_secure_password

  validates :email, presence: true, uniqueness: true, email: true
  validates :password_digest, length: { minimum: 6 }
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  validates :uuid, uniqueness: true

  def action_by(user)
    Likeable.find_by(video_id: id, user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def login(user)
    session[:user_id] = user.id
    @current_user = user
    flash[:notice] = 'Logged!!'
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user
    return true if current_user

    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in!"
    else
      redirect_to root_path, alert: "Email or password invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    user = User.new(user_params)
    message = ''
    if user.save
      login(user)
      message, status = "User created and logged !!!", 'success'
    else

      message, status = user.errors.full_messages.join(', '), 'error'
    end

    render json: { status: status, message: message }
  end

  private

  def user_params
    params.permit(:email, :password)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user, only: :share
  def index
    @videos = Video.includes(:user).page(params[:page]).per(5).decorate
  end

  def share
    @video_form = VideoForm.new(params[:url])


    if request.method == "POST"
      if @video_form.submit_by(current_user)
        redirect_to root_path, notice: "Share video success !!!"
      else
        render :share
      end
    end
  end

  def video_action
    like_form = LikeForm.new(params[:uuid], current_user, params[:status])

    if like_form.submit
      redirect_to root_path, notice: "Video #{params[:status]} success!!!"
    else
      redirect_to root_path, alert: like_form.errors
    end
  end

  def websocket
    render json: {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_alerts.html.slim
- if notice
    javascript:
      toastr["success"]("#{notice}", '', {"positionClass": "toast-bottom-full-width"});
- if alert
    javascript:
      toastr["error"]("#{alert}", '', {"positionClass": "toast-bottom-full-width"});

app/views/layouts/_footer.html.slim
hr
footer
  .container
    p make by shinvo

app/views/layouts/_header.html.slim
header
  .container
    .row
      .col-xs-2.col-sm-4.pt-4
        h2
          i.fa.fa-home.mr-1
          |Funny Videos
      .col-xs-10.col-sm-8.pt-4
        - if current_user
          = render 'layouts/logged'
        - else
          = render 'layouts/register_form'
  hr.mb-0

app/views/layouts/_logged.html.slim
.logged.pull-right
  span.mr-1 = current_user.email
  = link_to 'Share video', share_path, class: 'btn btn-warning mr-1'
  = link_to 'logout', sessions_destroy_path, method: :delete, class: 'btn btn-danger'

app/views/layouts/_register_form.html.slim
= form_tag sessions_create_path, class: 'form-inline pull-right', id: 'user_form'
  = email_field_tag :email, nil, class: 'form-control mr-1', placeholder: 'Enter email'
  = password_field_tag :password, nil, class: 'form-control mr-1', placeholder: 'Enter password'

  = submit_tag 'login', class: 'btn btn-success mr-1'

  button.btn.btn-primary#register_user type='button' register

app/views/layouts/application.html.slim
doctype html
html
  head
    title FunnyVideos
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"

  body
    = render 'layouts/alerts'
    = render partial: 'layouts/header'
    .container
      .container-fluid
        = yield
    = render partial: 'layouts/footer'

app/views/videos/_likeable.html.slim
-if current_user
  - likeable = video.action_by(current_user)
  span.pull-right
    - if likeable
      - if likeable.like?
        = link_to video_action_path(uuid: video.uuid, status: :dislike), method: :post
          i.fa.fa-thumbs-down
      - else
        = link_to video_action_path(uuid: video.uuid, status: :like), method: :post
          i.fa.fa-thumbs-up.pr-3
    - else
      = link_to video_action_path(uuid: video.uuid, status: :like), method: :post
        i.fa.fa-thumbs-up.pr-3
      = link_to video_action_path(uuid: video.uuid, status: :dislike), method: :post
        i.fa.fa-thumbs-down

app/views/videos/index.html.slim
- if @videos.present?
  - @videos.each do |video|
    .row
      .col-12.mt-3
        .card
          .card-horizontal
            .col-4.img-square-wrapper.px-0
              iframe width="100%" height="100%" src="https://www.youtube.com/embed/#{video.uuid}"
            .col-8.card-body
              h5.card-title
                = link_to video.title, video.video_url

                = render partial: 'likeable', locals: { video: video }
              p
                label = video.email
                br
                span.pr-1 = video.like_number
                i.fa.fa-thumbs-o-up.pr-3
                span.pr-1 = video.dislike_number
                i.fa.fa-thumbs-o-down
              p.card-text
                = video.description.truncate(300)
- else
  h2 Not have videos
p
  = paginate @videos

app/views/videos/share.html.slim
.share_form.d-flex.justify-content-center.h-100
  .card
    .card-header.text-center
      h3 Share a youtube video
    .card-body
      = form_tag share_path
        - if @video_form.errors.present?
          .alert.alert-danger
            = @video_form.errors.full_messages.join(', ')
        p Youtube URL :
        .input-group.form-group
          .input-group-prepend
            span.input-group-text
              i.fa.fa-link
          = text_field_tag :url, @video_form.url, placeholder: "Youtube URL", class: "form-control"
        .form-group.text-center
          button.btn.login_btn type="submit" share